; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[advanced_forum][version] = "2.0"

projects[ctools][version] = "1.2"

projects[calendar][version] = "3.4"

projects[cck][version] = "2.x-dev"

projects[comment_notify][version] = "1.1"

projects[content_access][version] = "1.2-beta1"

projects[date][version] = "2.6"

projects[drupad][version] = "1.13"

projects[entity][version] = "1.0"

projects[field_group][version] = "1.1"

projects[follow][version] = "1.0-alpha1"

projects[libraries][version] = "2.0"

projects[link][version] = "1.0"

projects[location][version] = "3.0-alpha1"

projects[mailchimp][version] = "2.9"

projects[menu_block][version] = "2.3"

projects[menu_breadcrumb][version] = "1.3"

projects[mollom][version] = "1.1"

projects[references][version] = "2.0"

projects[pathauto][version] = "1.2"

projects[save_draft][version] = "1.4"

projects[token][version] = "1.4"

projects[views][version] = "3.5"

projects[views_php][version] = "1.x-dev"

projects[wysiwyg][version] = "2.2"

; Themes
projects[blueprint][version] = "6.x-2.1"

projects[touch][version] = "1.7"

projects[opf-website][type] = "theme"
projects[opf-website][download][type] = "git"
projects[opf-website][download][url] = "git@github.com:openplanets/opf-website.git"
projects[opf-website][download][revision] = "ca288628307b2362152b78ebdcda4c5fd8e6d4e4"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[blueprint][download][type] = ""
libraries[blueprint][download][url] = ""
libraries[blueprint][directory_name] = "blueprint"
libraries[blueprint][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tinymce][download][type] = ""
libraries[tinymce][download][url] = ""
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[mailchimp][download][type] = ""
libraries[mailchimp][download][url] = ""
libraries[mailchimp][directory_name] = "mailchimp"
libraries[mailchimp][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"


